version: '3.0'
services:
  rasa:
    image: 'rasa/rasa:2.5.0-full'
    ports:
      - '5005:5005'
    volumes:
      - './:/app'
    command:
      - run
      - -m
      - models
      - --cors
      - "*"
      - --debug
  
  action-server:
    image: 'rasa/rasa-sdk:2.5.0'
    volumes:
      - './actions:/app/actions'
    ports:
      - '5055:5055'

  # mongo:
  #   image: 'mongo'
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: None
  #     MONGO_INITDB_ROOT_PASSWORD: None
  
  # mongo-express:  # this service is a MongoDB UI, and is optional
  #   image: 'mongo-express'
  #   ports:
  #     - '8081:8081'
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: None
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: None     
 
   
  
